// GENERATED by tools/floorplan/export_geometry.py — do not edit by hand.
//
// Room rectangles traced from the builder's architectural set, mirrored to
// match the as-built house (Elevation B, 'Garage Side: Right'). No rotation:
// the front facade sits along the BOTTOM facing the viewer, garage
// bottom-right. North points LEFT.
//
// Plan space is 1300x1600 at 26px per foot.

export interface PlanRoom {
  name: string;
  /** rect in plan space, already mirrored */
  x: number; y: number; w: number; h: number;
  /** unheated: garage, porch, unexcavated */
  cold: boolean;
  /** floor material from the signed selections sheet */
  material: string | null;
  /** builder's finished-room schedule, sq ft */
  sqft: number | null;
  /** accent wall paint, if the room has one */
  paint: [number, number, number] | null;
}

export const PLAN_W = 1300;
export const PLAN_H = 1600;
export const PX_PER_FT = 26;

export const FLOORS: Record<string, { title: string; rooms: PlanRoom[] }> =
{
  "fp_main": {
    "title": "MAIN FLOOR",
    "rooms": [
      {
        "name": "Study",
        "x": 886,
        "y": 53,
        "w": 346,
        "h": 307,
        "cold": false,
        "material": "carpet",
        "sqft": 120,
        "paint": null
      },
      {
        "name": "Dining",
        "x": 535,
        "y": 53,
        "w": 346,
        "h": 359,
        "cold": false,
        "material": "wood",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Great Room",
        "x": 67,
        "y": 261,
        "w": 463,
        "h": 411,
        "cold": false,
        "material": "wood",
        "sqft": 240,
        "paint": null
      },
      {
        "name": "Bath",
        "x": 1029,
        "y": 365,
        "w": 203,
        "h": 203,
        "cold": false,
        "material": "wood",
        "sqft": 38,
        "paint": null
      },
      {
        "name": "W.I.C.",
        "x": 886,
        "y": 365,
        "w": 138,
        "h": 203,
        "cold": false,
        "material": "carpet",
        "sqft": 33,
        "paint": null
      },
      {
        "name": "Kitchen",
        "x": 535,
        "y": 417,
        "w": 346,
        "h": 307,
        "cold": false,
        "material": "wood",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Mud",
        "x": 886,
        "y": 573,
        "w": 346,
        "h": 281,
        "cold": false,
        "material": "vinyl_gs",
        "sqft": 107,
        "paint": null
      },
      {
        "name": "Entry",
        "x": 249,
        "y": 677,
        "w": 281,
        "h": 255,
        "cold": false,
        "material": "wood",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Stairs",
        "x": 67,
        "y": 677,
        "w": 177,
        "h": 260,
        "cold": false,
        "material": "carpet",
        "sqft": 90,
        "paint": null
      },
      {
        "name": "Pantry",
        "x": 717,
        "y": 729,
        "w": 164,
        "h": 125,
        "cold": false,
        "material": "wood",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Back Hall",
        "x": 535,
        "y": 729,
        "w": 182,
        "h": 125,
        "cold": false,
        "material": "wood",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Garage",
        "x": 534,
        "y": 858,
        "w": 699,
        "h": 569,
        "cold": true,
        "material": "concrete",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Porch",
        "x": 66,
        "y": 936,
        "w": 387,
        "h": 153,
        "cold": true,
        "material": "wood",
        "sqft": null,
        "paint": null
      }
    ]
  },
  "fp_upper": {
    "title": "UPPER FLOOR",
    "rooms": [
      {
        "name": "Bedroom 4",
        "x": 873,
        "y": 53,
        "w": 359,
        "h": 307,
        "cold": false,
        "material": "carpet",
        "sqft": 200,
        "paint": [
          88,
          122,
          134
        ]
      },
      {
        "name": "Bath 2",
        "x": 717,
        "y": 53,
        "w": 151,
        "h": 203,
        "cold": false,
        "material": "vinyl_ir",
        "sqft": 53,
        "paint": null
      },
      {
        "name": "Master Bath",
        "x": 509,
        "y": 53,
        "w": 203,
        "h": 255,
        "cold": false,
        "material": "tile",
        "sqft": 142,
        "paint": null
      },
      {
        "name": "Master Bedroom",
        "x": 67,
        "y": 157,
        "w": 437,
        "h": 411,
        "cold": false,
        "material": "carpet",
        "sqft": 241,
        "paint": null
      },
      {
        "name": "Laundry",
        "x": 717,
        "y": 313,
        "w": 151,
        "h": 151,
        "cold": false,
        "material": "vinyl_tb",
        "sqft": 82,
        "paint": null
      },
      {
        "name": "W.I.C.",
        "x": 509,
        "y": 313,
        "w": 203,
        "h": 151,
        "cold": false,
        "material": "carpet",
        "sqft": 68,
        "paint": null
      },
      {
        "name": "Bath 1",
        "x": 1029,
        "y": 365,
        "w": 203,
        "h": 203,
        "cold": false,
        "material": "vinyl_ir",
        "sqft": 76,
        "paint": null
      },
      {
        "name": "Hall",
        "x": 873,
        "y": 365,
        "w": 151,
        "h": 203,
        "cold": false,
        "material": "carpet",
        "sqft": 116,
        "paint": null
      },
      {
        "name": "Bedroom 3",
        "x": 873,
        "y": 573,
        "w": 359,
        "h": 307,
        "cold": false,
        "material": "carpet",
        "sqft": 209,
        "paint": [
          94,
          132,
          116
        ]
      },
      {
        "name": "Bedroom 2",
        "x": 457,
        "y": 573,
        "w": 411,
        "h": 307,
        "cold": false,
        "material": "carpet",
        "sqft": 179,
        "paint": [
          96,
          118,
          138
        ]
      },
      {
        "name": "Loft",
        "x": 249,
        "y": 573,
        "w": 203,
        "h": 255,
        "cold": false,
        "material": "carpet",
        "sqft": 89,
        "paint": null
      },
      {
        "name": "Stairs",
        "x": 67,
        "y": 573,
        "w": 177,
        "h": 307,
        "cold": false,
        "material": "carpet",
        "sqft": 90,
        "paint": null
      },
      {
        "name": "",
        "x": 505,
        "y": 460,
        "w": 370,
        "h": 110,
        "cold": false,
        "material": "carpet",
        "sqft": null,
        "paint": null
      },
      {
        "name": "",
        "x": 710,
        "y": 250,
        "w": 165,
        "h": 65,
        "cold": false,
        "material": "carpet",
        "sqft": null,
        "paint": null
      }
    ]
  },
  "fp_lower": {
    "title": "BASEMENT",
    "rooms": [
      {
        "name": "Future Bedroom",
        "x": 872,
        "y": 52,
        "w": 361,
        "h": 309,
        "cold": true,
        "material": "concrete",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Rec Room (future)",
        "x": 456,
        "y": 104,
        "w": 413,
        "h": 309,
        "cold": true,
        "material": "concrete",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Family Room",
        "x": 67,
        "y": 157,
        "w": 385,
        "h": 567,
        "cold": false,
        "material": "carpet",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Future Bath",
        "x": 1028,
        "y": 364,
        "w": 205,
        "h": 205,
        "cold": true,
        "material": "vinyl_gs",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Mechanical",
        "x": 717,
        "y": 417,
        "w": 307,
        "h": 255,
        "cold": false,
        "material": "concrete",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Hall",
        "x": 457,
        "y": 417,
        "w": 255,
        "h": 255,
        "cold": false,
        "material": "carpet",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Bedroom",
        "x": 873,
        "y": 677,
        "w": 359,
        "h": 255,
        "cold": false,
        "material": "carpet",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Stairs",
        "x": 67,
        "y": 729,
        "w": 177,
        "h": 307,
        "cold": false,
        "material": "carpet",
        "sqft": null,
        "paint": null
      },
      {
        "name": "",
        "x": 873,
        "y": 364,
        "w": 152,
        "h": 49,
        "cold": true,
        "material": "concrete",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Unexcavated",
        "x": 534,
        "y": 988,
        "w": 699,
        "h": 439,
        "cold": true,
        "material": "concrete",
        "sqft": null,
        "paint": null
      }
    ]
  }
};

export const MATERIAL_COLORS: Record<string, [number, number, number]> = {
  "wood": [
    56,
    44,
    34
  ],
  "carpet": [
    57,
    53,
    48
  ],
  "vinyl_gs": [
    52,
    56,
    62
  ],
  "vinyl_tb": [
    58,
    47,
    37
  ],
  "vinyl_ir": [
    47,
    51,
    57
  ],
  "tile": [
    55,
    59,
    64
  ],
  "concrete": [
    35,
    38,
    43
  ]
};
