// GENERATED by export_geometry — do not edit by hand.
//
// Rooms traced from the builder's set, mirrored to match the as-built house
// (Elevation B, 'Garage Side: Right'). No rotation: the front facade sits
// along the BOTTOM facing the viewer. North points LEFT.
//
// The canvas is taller than the traced footprint because the deck sits
// outside it, off the back wall; Y_SHIFT moves everything down to suit.

export interface PlanRoom {
  name: string;
  x: number; y: number; w: number; h: number;
  cold: boolean;
  material: string | null;
  sqft: number | null;
  paint: [number, number, number] | null;
}

export const PLAN_W = 1300;
export const PLAN_H = 1920;
export const PX_PER_FT = 26;

export const FLOORS: Record<string, { title: string; rooms: PlanRoom[] }> =
{
  "fp_main": {
    "title": "MAIN FLOOR",
    "rooms": [
      {
        "name": "Study",
        "x": 886,
        "y": 373,
        "w": 346,
        "h": 307,
        "cold": false,
        "material": "carpet",
        "sqft": 120,
        "paint": null
      },
      {
        "name": "Dining",
        "x": 535,
        "y": 373,
        "w": 346,
        "h": 359,
        "cold": false,
        "material": "wood",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Great Room",
        "x": 67,
        "y": 581,
        "w": 463,
        "h": 411,
        "cold": false,
        "material": "wood",
        "sqft": 240,
        "paint": null
      },
      {
        "name": "Bath",
        "x": 1029,
        "y": 685,
        "w": 203,
        "h": 203,
        "cold": false,
        "material": "wood",
        "sqft": 38,
        "paint": null
      },
      {
        "name": "Back Hall",
        "x": 886,
        "y": 685,
        "w": 138,
        "h": 203,
        "cold": false,
        "material": "wood",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Kitchen",
        "x": 535,
        "y": 737,
        "w": 346,
        "h": 307,
        "cold": false,
        "material": "wood",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Mud",
        "x": 886,
        "y": 893,
        "w": 346,
        "h": 281,
        "cold": false,
        "material": "vinyl_gs",
        "sqft": 107,
        "paint": null
      },
      {
        "name": "Entry",
        "x": 249,
        "y": 997,
        "w": 281,
        "h": 255,
        "cold": false,
        "material": "wood",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Stairs",
        "x": 67,
        "y": 997,
        "w": 177,
        "h": 260,
        "cold": false,
        "material": "carpet",
        "sqft": 90,
        "paint": null
      },
      {
        "name": "",
        "x": 717,
        "y": 1049,
        "w": 164,
        "h": 125,
        "cold": false,
        "material": "wood",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Pantry",
        "x": 535,
        "y": 1049,
        "w": 182,
        "h": 125,
        "cold": false,
        "material": "wood",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Deck",
        "x": 535,
        "y": 20,
        "w": 697,
        "h": 353,
        "cold": true,
        "material": "wood",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Double Bay",
        "x": 767,
        "y": 1178,
        "w": 466,
        "h": 569,
        "cold": true,
        "material": "concrete",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Single Bay",
        "x": 534,
        "y": 1178,
        "w": 233,
        "h": 569,
        "cold": true,
        "material": "concrete",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Porch",
        "x": 66,
        "y": 1256,
        "w": 468,
        "h": 153,
        "cold": true,
        "material": "wood",
        "sqft": null,
        "paint": null
      }
    ]
  },
  "fp_upper": {
    "title": "UPPER FLOOR",
    "rooms": [
      {
        "name": "Bedroom 4",
        "x": 873,
        "y": 373,
        "w": 359,
        "h": 307,
        "cold": false,
        "material": "carpet",
        "sqft": 200,
        "paint": [
          88,
          122,
          134
        ]
      },
      {
        "name": "Bath 2",
        "x": 717,
        "y": 373,
        "w": 151,
        "h": 203,
        "cold": false,
        "material": "vinyl_ir",
        "sqft": 53,
        "paint": null
      },
      {
        "name": "Master Bath",
        "x": 509,
        "y": 373,
        "w": 203,
        "h": 255,
        "cold": false,
        "material": "tile",
        "sqft": 142,
        "paint": null
      },
      {
        "name": "Master Bedroom",
        "x": 67,
        "y": 477,
        "w": 437,
        "h": 411,
        "cold": false,
        "material": "carpet",
        "sqft": 241,
        "paint": null
      },
      {
        "name": "Laundry",
        "x": 717,
        "y": 633,
        "w": 151,
        "h": 151,
        "cold": false,
        "material": "vinyl_tb",
        "sqft": 82,
        "paint": null
      },
      {
        "name": "W.I.C.",
        "x": 509,
        "y": 633,
        "w": 203,
        "h": 151,
        "cold": false,
        "material": null,
        "sqft": 68,
        "paint": null
      },
      {
        "name": "Bath 1",
        "x": 1029,
        "y": 685,
        "w": 203,
        "h": 203,
        "cold": false,
        "material": "vinyl_ir",
        "sqft": 76,
        "paint": null
      },
      {
        "name": "Hall",
        "x": 873,
        "y": 685,
        "w": 151,
        "h": 203,
        "cold": false,
        "material": "carpet",
        "sqft": 116,
        "paint": null
      },
      {
        "name": "Bedroom 3",
        "x": 873,
        "y": 893,
        "w": 359,
        "h": 307,
        "cold": false,
        "material": "carpet",
        "sqft": 209,
        "paint": [
          94,
          132,
          116
        ]
      },
      {
        "name": "Bedroom 2",
        "x": 457,
        "y": 893,
        "w": 411,
        "h": 307,
        "cold": false,
        "material": "carpet",
        "sqft": 179,
        "paint": [
          96,
          118,
          138
        ]
      },
      {
        "name": "Loft",
        "x": 249,
        "y": 893,
        "w": 203,
        "h": 255,
        "cold": false,
        "material": "carpet",
        "sqft": 89,
        "paint": null
      },
      {
        "name": "Stairs",
        "x": 67,
        "y": 893,
        "w": 177,
        "h": 307,
        "cold": false,
        "material": "carpet",
        "sqft": 90,
        "paint": null
      },
      {
        "name": "",
        "x": 505,
        "y": 780,
        "w": 370,
        "h": 110,
        "cold": false,
        "material": "carpet",
        "sqft": null,
        "paint": null
      },
      {
        "name": "",
        "x": 710,
        "y": 570,
        "w": 165,
        "h": 65,
        "cold": false,
        "material": "carpet",
        "sqft": null,
        "paint": null
      }
    ]
  },
  "fp_lower": {
    "title": "BASEMENT",
    "rooms": [
      {
        "name": "Future Bedroom",
        "x": 872,
        "y": 372,
        "w": 361,
        "h": 309,
        "cold": true,
        "material": "concrete",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Rec Room (future)",
        "x": 456,
        "y": 424,
        "w": 413,
        "h": 309,
        "cold": true,
        "material": "concrete",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Family Room",
        "x": 67,
        "y": 477,
        "w": 385,
        "h": 567,
        "cold": false,
        "material": "carpet",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Future Bath",
        "x": 1028,
        "y": 684,
        "w": 205,
        "h": 205,
        "cold": true,
        "material": "vinyl_gs",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Mechanical",
        "x": 717,
        "y": 737,
        "w": 307,
        "h": 255,
        "cold": false,
        "material": "concrete",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Hall",
        "x": 457,
        "y": 737,
        "w": 255,
        "h": 255,
        "cold": false,
        "material": "carpet",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Bedroom",
        "x": 873,
        "y": 997,
        "w": 359,
        "h": 255,
        "cold": false,
        "material": "carpet",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Stairs",
        "x": 67,
        "y": 1049,
        "w": 177,
        "h": 307,
        "cold": false,
        "material": "carpet",
        "sqft": null,
        "paint": null
      },
      {
        "name": "",
        "x": 873,
        "y": 684,
        "w": 152,
        "h": 49,
        "cold": true,
        "material": "concrete",
        "sqft": null,
        "paint": null
      },
      {
        "name": "Unexcavated",
        "x": 534,
        "y": 1308,
        "w": 699,
        "h": 439,
        "cold": true,
        "material": "concrete",
        "sqft": null,
        "paint": null
      }
    ]
  }
};

export const MATERIAL_COLORS: Record<string, [number, number, number]> = {
  "wood": [
    56,
    44,
    34
  ],
  "carpet": [
    57,
    53,
    48
  ],
  "vinyl_gs": [
    52,
    56,
    62
  ],
  "vinyl_tb": [
    58,
    47,
    37
  ],
  "vinyl_ir": [
    47,
    51,
    57
  ],
  "tile": [
    55,
    59,
    64
  ],
  "concrete": [
    35,
    38,
    43
  ]
};
